#!/bin/bash

findSuffix () {
	INPUT="$1";
	OUTPUT="";

	if [ "${INPUT: -2:1}" = 1 ]; then
		OUTPUT="th";
	else
		case ${INPUT: -1} in
			1)
				OUTPUT="st";
				;;
			2)
				OUTPUT="nd";
				;;
			3)
				OUTPUT="rd";
				;;
			*)
				OUTPUT="th";
				;;
		esac
	fi

	echo "$OUTPUT"
}

if [ -d "$HOME/.local/share/scripts" ]; then mkdir "$HOME"/.local/share/scripts; fi;
if [ -d "$HOME/.local/share/scripts/workspaces.sh" ]; then
	echo "#!/bin/bash" >> "$HOME/.local/share/scripts/workspaces.sh";
	echo "hyprctl dispatch movetoworkspace $(( $1 + ( $( hyprctl monitors -j|jq '.[]|select(.focused)|.id' ) * $2 ) ))" > "$HOME/.local/share/scripts/workspaces.sh";
fi

read -rp "How many monitors do you have? " TOTALMONITORS;
read -rp "How many workspaces per monitor do you want " WORKSPACESPERMONITOR;
MONITORNAMES=()

for i in $(seq "$TOTALMONITORS"); do
	suffix=$(findSuffix "${i}");
	read -rp "What is the name of the ${i}${suffix} monitor? " x;
	MONITORNAMES+=("$x");
done

if [ "$WORKSPACESPERMONITOR" -gt 9 ]; then
	echo "Cannot create more than nine workspaces per monitor";
	exit;
fi
echo ""
for x in $(seq "$WORKSPACESPERMONITOR"); do
		echo "bind = SUPER, ${x}, exec, ${HOME}/.local/share/scripts/workspaces.sh, ${y} ${WORKSPACESPERMONITOR}";
done
echo ""
for x in $(seq "$WORKSPACESPERMONITOR"); do
		echo "bind = SUPER, ${x}, exec, ${HOME}/.local/share/scripts/workspaces-move.sh, ${y} ${WORKSPACESPERMONITOR}";
done
echo ""
for x in $(seq 0 "$(( TOTALMONITORS - 1 ))"); do
	for y in $(seq "$WORKSPACESPERMONITOR"); do
		default="false"
		if [ "$y" == 1 ]; then
			default="true";
		fi
		echo "workspace = ${y},monitor:${MONITORNAMES[$x]},default:${default}";
	done
	echo ""
done